config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/tasks/', permanent=False)),
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls')),        
]

core/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path("", views.index ,  name="index"),
    path("newyear/", views.index ,  name="newyear"),
    path("", views.hello,  name="hello"),
    
]

hello/urls.py
from django.urls import path
from .views import index, megha, hello, greet

urlpatterns = [
    path('', index, name='index'),
    path('hello/', hello, name='hello'),
    path('megha/', megha, name='megha'),
    path('<str:name>/', greet, name='greet'),
    
]

newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
    # path('', index, name='newyear'),

]

tasks/urls.py
from django.urls import path
from tasks import views 

app_name = "tasks"
urlpatterns = [
    path("", views.index ,  name="index"),
    path("add/", views.add ,  name="add"),
    path("clear/", views.clear ,  name="clear")
]

core/models.py
from django.db import models

# Create your models here.

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

core/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return HttpResponse ("Hello, world. You're at the core index.")

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return HttpResponse("Hello")

def megha(request):
    return HttpResponse("Hello Megha")

def hello(request):
    return HttpResponse("Hello, World!")

def greet(request , name):
    return HttpResponse(f"Hello, {name.capitalize()}!")

newyear/views.py
import datetime
from django.shortcuts import render


def index(request):
    now = datetime.datetime.now()
    return render(request, 'newyear/index.html',{
        "newyear": now.month == 1 and now.day == 1
    })

tasks/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
        
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })


def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            if "tasks" not in request.session:
                request.session["tasks"] = []
            request.session["tasks"] += [task]
            request.session.modified = True
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

def clear(request):
    request.session["tasks"] = []
    return HttpResponseRedirect(reverse("tasks:index"))

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello </title>
</head>
<body>
    <h1>Hello! {{ name }}</h1>
    <p>This is a simple Django template greeting.</p>
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello Page</title>
</head>
<body>
    <h1>Hello, welcome to the Hello Page!</h1>
    <p>This is a simple Django template.</p>
</body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello </title>
    <link rel="stylesheet"  href="{% static 'newyear/styles.css' %}">
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
        <p>Happy New Year!</p>
    {% else %}
        <h1>No</h1>
        <p>Welcome to the page ,NO Newyear.</p>
    {% endif %}
        

    
</body>

</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}
{% block body %}

    <h1>Add Task</h1> 
    <form action="{% url 'tasks:add' %}" method="post">
         {% csrf_token %}
      {{ form }}
       <input type="submit" >
    </form>
    <a href="{% url 'tasks:index' %}">Back to Task List</a>

{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Task List</h1>
    <ul>
      <!-- <li>item one</li>
        <li>item two</li>
        <li>item three</li> -->

      {% for task in tasks %}
      <li>{{ task }}</li>
      {% empty %}
      <li>No tasks yet!</li>
      {% endfor %}

    </ul>
    <a href="{% url 'tasks:add' %}">Add a new task</a>
    
    {% if tasks %}
    | <a href="{% url 'tasks:clear' %}" onclick="return confirm('Are you sure you want to clear all tasks?')">Clear all tasks</a>
    {% endif %}
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>